{*******************************************************}
{                                                       }
{           CodeGear Delphi Runtime Library             }
{                                                       }
{ Copyright(c) 1995-2013 Embarcadero Technologies, Inc. }
{                                                       }
{*******************************************************}

const
  AndroidLib            = '/usr/lib/libandroid.so';
  AndroidJniGraphicsLib = '/usr/lib/libjnigraphics.so';
  AndroidEglLib         = '/usr/lib/libEGL.so';
  AndroidGlesLib        = '/usr/lib/libGLESv1_CM.so';
  AndroidGles2Lib       = '/usr/lib/libGLESv2.so';
  AndroidLogLib         = '/usr/lib/liblog.so';
  AndroidOpenSlesLib    = '/usr/lib/libOpenSLES.so';